[package]
name = "xhttp2"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
byteorder = "1"
fibers = "0.1"
futures = "0.1"
handy_async = "0.2"
hpack_codec = "0.1"
trackable = "0.2"

[dev-dependencies]
clap = "2"
